name: Build HuskSync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle with Java 21
        uses: gradle/gradle-build-action@v3
        with:
          java-version: 21
          java-distribution: temurin

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: HuskSync-JAR
          path: build/libs/*.jar
